# Generated by Django 4.0.5 on 2023-10-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('datanascimento', models.DateField(max_length=100)),
            ],
        ),
    ]
